"use strict";
exports.__esModule = true;
var ncmb_ts_1 = require("./ncmb.ts");
var read_json_ts_1 = require("https://deno.land/std/fs/read_json.ts");
var config = await read_json_ts_1.readJson('./config.json');
var applicationKey = config.applicationKey;
var clientKey = config.clientKey;
var ncmb = new ncmb_ts_1.NCMB(applicationKey, clientKey);
var user = await ncmb_ts_1.NCMBUser.login('tester', 'tester');
console.log(user);
